version: '3.5'

services:
  poetry:
    container_name: poetry-container-command
    build: .
    command: bash -c "poetry config virtualenvs.create false && poetry config pypi-token.pypi ${token} && poetry version ${version} && poetry build && poetry publish"
    depends_on:
      - library-db

  library-db:
    container_name: lappis-mongo
    image: mongo:4.0.3
    restart: always
    ports:
      - 27017:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=lappis
    - MONGO_INITDB_ROOT_PASSWORD=lappis

  metabase:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - library-db
  
  postgres:
    container_name: lappis-postgres
    image: postgres:12.0
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: lappis
      POSTGRES_PASSWORD: lappis
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:




    
  