version: '3.5'

services:
  db:
    container_name: mongo
    image: mongo:4.0.3
    ports:
      - 27017:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=lappis
    - MONGO_INITDB_ROOT_PASSWORD=lappis
    


    
  