name: DEPLOY CI

on: 
  push:
    branches:
      - master

jobs:
  build:
  runs-on: ubuntu-latest 
    steps:
    - name: verificando os arquivos na master
      uses: actions/checkout@v2
    - name: inserindo e verificando a variante para o funcionamento do projeto
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: instalando a biblioteca poetry
      run: python -m pip install poetry
    - name: instalando a biblioteca que cria documentos sphinx
      run: sudo apt install --allow-unauthenticated python3-sphinx -y
    - name: instalando as dependencias do projeto com o poetry
      run: |
        poetry install
    - name: instalando o lint
      run: |
        pip install pylint
        pylint src
    continue-on-error: true
    - name: utilizando o Sphinx para gerar documentação
      run: sphinx-build -b html docs/ docs/build/
    - name: publicando na pypi
      run |
        poetry config pypi-token.pypi ${{ secrets.TOKEN}}
        poetry publish --username __token__ -v


      
